import 'package:flutter/material.dart';
import '../roles_db.dart';

const Map<String, CareerRole> businessRoles = {
  'product_manager': CareerRole(
    slug: 'product_manager',
    name: 'Product Manager',
    icon: 'target',
    category: 'Business & Product',
    demand: 'High',
    salary: '₹8–35 LPA',
    color: Color(0xFFF59E0B),
    description: 'Product Managers define product strategy, work with cross-functional teams, and ensure the right things get built to maximise user and business value.',
    requiredSkills: ['Product Strategy', 'User Research', 'Data Analysis', 'Roadmapping', 'Stakeholder Management', 'Agile', 'SQL', 'Wireframing'],
    weights: {'Product Strategy': 1.6, 'Roadmapping': 1.4, 'Stakeholder Management': 1.3, 'User Research': 1.1, 'Agile': 1.0, 'SQL': 0.6},
    requiredLevels: {'Product Strategy': 80, 'Roadmapping': 80, 'Stakeholder Management': 75, 'User Research': 70, 'Agile': 70, 'SQL': 40},
    tools: ['Jira', 'Notion', 'Figma', 'Amplitude', 'Mixpanel', 'SQL'],
    aiTips: [
      'Practice writing PRDs (Product Requirements Documents) for real products you use.',
      'Learn basic SQL to analyse product data independently without needing a data analyst.',
      'Study prioritisation frameworks like RICE, ICE, and OKRs.',
      'Build a product portfolio with detailed teardowns of apps you admire.',
    ],
    qualificationRequired: false,
    qualifications: [],
    careerCluster: 'Business',
    qualificationNote: 'A degree is preferred (e.g., MBA or CS), but strong product sense and a portfolio are more important.',
  ),
  'business_analyst': CareerRole(
    slug: 'business_analyst',
    name: 'Business Analyst',
    icon: 'business',
    category: 'Business & Product',
    demand: 'High',
    salary: '₹6–20 LPA',
    color: Color(0xFFEAB308),
    description: 'Business Analysts bridge the gap between IT and the business using data analytics to assess processes, determine requirements, and deliver data-driven recommendations.',
    requiredSkills: ['Business Analysis', 'SQL', 'Requirements Gathering', 'Process Modeling', 'Data Visualization', 'Stakeholder Management', 'Agile', 'Excel'],
    weights: {'Business Analysis': 1.5, 'Requirements Gathering': 1.5, 'SQL': 1.2, 'Process Modeling': 1.2, 'Stakeholder Management': 1.0, 'Excel': 0.8},
    requiredLevels: {'Business Analysis': 85, 'Requirements Gathering': 80, 'SQL': 70, 'Process Modeling': 75, 'Stakeholder Management': 75, 'Excel': 80},
    tools: ['Excel', 'SQL', 'Tableau', 'Jira', 'Confluence', 'Power BI'],
    aiTips: [
      'Master advanced Excel and SQL; they are the bread and butter of this role.',
      'Learn how to translate complex business needs into clear technical requirements.',
      'Study process modeling techniques like BPMN.',
    ],
    qualificationRequired: false,
    qualifications: [],
    careerCluster: 'Business',
    qualificationNote: 'Typically requires a Bachelor\'s degree in Business or related field, but skills in analytics weigh heavily.',
  ),
  'operations_manager': CareerRole(
    slug: 'operations_manager',
    name: 'Operations Manager',
    icon: 'admin',
    category: 'Business & Product',
    demand: 'Medium',
    salary: '₹7–25 LPA',
    color: Color(0xFFD97706),
    description: 'Operations Managers oversee productivity and efficiency of business operations, analyzing metrics and improving processes to ensure smooth organizational workflows.',
    requiredSkills: ['Operations Management', 'Process Improvement', 'Data Analysis', 'Leadership', 'Supply Chain Management', 'Budgeting', 'Project Management'],
    weights: {'Operations Management': 1.5, 'Process Improvement': 1.4, 'Leadership': 1.3, 'Project Management': 1.2, 'Data Analysis': 1.0, 'Budgeting': 0.8},
    requiredLevels: {'Operations Management': 85, 'Process Improvement': 80, 'Leadership': 80, 'Project Management': 75, 'Data Analysis': 65, 'Budgeting': 70},
    tools: ['ERP Systems', 'Excel', 'Asana', 'Tableau', 'Slack'],
    aiTips: [
      'Focus on learning Lean Six Sigma or other process improvement methodologies.',
      'Develop strong leadership and cross-team communication skills.',
      'Learn to balance cost-efficiency with quality control.',
    ],
    qualificationRequired: false,
    qualifications: [],
    careerCluster: 'Business',
    qualificationNote: 'Often requires a business degree or MBA, but proven operational experience is heavily favored.',
  ),
};
