import 'package:flutter/material.dart';
import '../roles_db.dart';

const Map<String, CareerRole> designRoles = {
  'ux_designer': CareerRole(
    slug: 'ux_designer',
    name: 'UX/UI Designer',
    icon: 'pen_tool',
    category: 'Design',
    demand: 'Very High',
    salary: '₹4–18 LPA',
    color: Color(0xFFA855F7),
    description: 'UX Designers craft user-centred digital products by conducting research, building wireframes, and delivering polished prototypes that solve real user problems.',
    requiredSkills: ['Figma', 'User Research', 'Wireframing', 'Prototyping', 'Design Systems', 'Usability Testing', 'UX Writing', 'Adobe XD'],
    weights: {'Figma': 1.5, 'User Research': 1.4, 'Prototyping': 1.2, 'Wireframing': 1.1, 'Design Systems': 1.1, 'Usability Testing': 1.0, 'UX Writing': 0.9, 'Adobe XD': 0.7},
    requiredLevels: {'Figma': 85, 'User Research': 80, 'Prototyping': 75, 'Wireframing': 70, 'Design Systems': 75, 'Usability Testing': 70, 'UX Writing': 65, 'Adobe XD': 50},
    tools: ['Figma', 'Adobe XD', 'Maze', 'Hotjar', 'Miro', 'Notion'],
    aiTips: [
      'Master Figma Auto Layout and Components to speed up design work significantly.',
      'Build a portfolio with 3–5 detailed case studies that include your research process.',
      'Learn basic HTML/CSS to communicate better with developers.',
      'Practice conducting user interviews and synthesising findings into actionable insights.',
    ],
    qualificationRequired: false,
    qualifications: [],
    careerCluster: 'Design',
    qualificationNote: 'No mandatory degree; employers evaluate portfolio and design thinking skills.',
  ),
  'graphic_designer': CareerRole(
    slug: 'graphic_designer',
    name: 'Graphic Designer',
    icon: 'design',
    category: 'Design',
    demand: 'High',
    salary: '₹3–12 LPA',
    color: Color(0xFFC084FC),
    description: 'Graphic Designers create visual concepts to communicate ideas that inspire, inform, and captivate consumers, developing overall layout and production design.',
    requiredSkills: ['Adobe Illustrator', 'Adobe Photoshop', 'Typography', 'Color Theory', 'Branding', 'Layout Design', 'InDesign', 'Creativity'],
    weights: {'Adobe Illustrator': 1.5, 'Adobe Photoshop': 1.4, 'Typography': 1.3, 'Branding': 1.2, 'Layout Design': 1.1, 'InDesign': 0.8, 'Color Theory': 1.1, 'Creativity': 1.0},
    requiredLevels: {'Adobe Illustrator': 85, 'Adobe Photoshop': 80, 'Typography': 80, 'Branding': 75, 'Layout Design': 75, 'InDesign': 65, 'Color Theory': 80, 'Creativity': 85},
    tools: ['Adobe Illustrator', 'Adobe Photoshop', 'Adobe InDesign', 'Figma', 'CorelDRAW'],
    aiTips: [
      'Focus heavily on typography and color theory, not just tool knowledge.',
      'Create a digital portfolio showcasing diverse projects (logos, social media, print).',
      'Understand basic marketing principles to design better ad creatives.',
    ],
    qualificationRequired: false,
    qualifications: [],
    careerCluster: 'Design',
    qualificationNote: 'Portfolio is king. Formal design degree is a bonus but not strictly required.',
  ),
  'motion_designer': CareerRole(
    slug: 'motion_designer',
    name: 'Motion Designer',
    icon: 'video',
    category: 'Design',
    demand: 'Medium',
    salary: '₹4–15 LPA',
    color: Color(0xFFD8B4FE),
    description: 'Motion Designers bring static designs to life through animation and visual effects, often working on UI animations, marketing videos, and film.',
    requiredSkills: ['After Effects', 'Animation Principles', 'Premiere Pro', 'Motion Graphics', 'Storyboarding', 'Typography', '3D Animation', 'Cinema 4D'],
    weights: {'After Effects': 1.6, 'Motion Graphics': 1.5, 'Animation Principles': 1.4, 'Premiere Pro': 1.2, 'Storyboarding': 1.0, 'Cinema 4D': 0.8, 'Typography': 1.2, '3D Animation': 1.0},
    requiredLevels: {'After Effects': 85, 'Motion Graphics': 85, 'Animation Principles': 80, 'Premiere Pro': 75, 'Storyboarding': 70, 'Cinema 4D': 50, 'Typography': 70, '3D Animation': 60},
    tools: ['Adobe After Effects', 'Adobe Premiere Pro', 'Cinema 4D', 'Blender', 'Figma'],
    aiTips: [
      'Master the 12 principles of animation to make movement feel natural.',
      'Learn basic 3D workflows to add depth to your 2D motion graphics.',
      'Create a compelling showreel under 1 minute showing your best work.',
    ],
    qualificationRequired: false,
    qualifications: [],
    careerCluster: 'Design',
    qualificationNote: 'A strong demo reel is the primary hiring requirement.',
  ),
};
