import 'package:flutter/material.dart';
import '../roles_db.dart';

const Map<String, CareerRole> educationRoles = {
  'school_teacher': CareerRole(
    slug: 'school_teacher',
    name: 'School Teacher',
    icon: 'education',
    category: 'Education',
    demand: 'Very High',
    salary: '₹2.5–9 LPA',
    color: Color(0xFF6366F1),
    description: 'School Teachers prepare and educate students for the world by delivering curriculums, assessing progress, and fostering character development.',
    requiredSkills: ['Pedagogy', 'Classroom Management', 'Lesson Planning', 'Curriculum Design', 'Child Psychology', 'Communication', 'Subject Expertise'],
    weights: {'Pedagogy': 1.6, 'Classroom Management': 1.5, 'Lesson Planning': 1.4, 'Communication': 1.3, 'Subject Expertise': 1.2, 'Child Psychology': 1.0},
    requiredLevels: {'Pedagogy': 85, 'Classroom Management': 80, 'Lesson Planning': 80, 'Communication': 90, 'Subject Expertise': 85, 'Child Psychology': 70},
    tools: ['Google Classroom', 'Blackboard', 'PowerPoint', 'Zoom'],
    aiTips: [
      'Develop extreme patience and empathy; these are your core soft skills.',
      'Learn to use ed-tech tools creatively to keep students engaged.',
      'Pass the required state eligibility tests (e.g., CTET).',
    ],
    qualificationRequired: true,
    qualifications: ['Bachelor of Education (B.Ed)', 'State Teacher Eligibility Test (TET/CTET)'],
    qualificationNote: 'Formal teaching degrees and state-level certifications are legally required to teach in recognized schools.',
  ),
  'instructional_designer': CareerRole(
    slug: 'instructional_designer',
    name: 'Instructional Designer',
    icon: 'education',
    category: 'Education',
    demand: 'High',
    salary: '₹4–15 LPA',
    color: Color(0xFF8B5CF6),
    description: 'Instructional Designers systematically design, develop, and deliver instructional materials and experiences, often in corporate or digital learning environments.',
    requiredSkills: ['Instructional Design', 'E-Learning Development', 'Storyboarding', 'Adult Learning Theory', 'Articulate Storyline', 'LMS Administration', 'Video Editing'],
    weights: {'Instructional Design': 1.7, 'E-Learning Development': 1.5, 'Adult Learning Theory': 1.4, 'Articulate Storyline': 1.3, 'Storyboarding': 1.2, 'LMS Administration': 1.0},
    requiredLevels: {'Instructional Design': 85, 'E-Learning Development': 80, 'Adult Learning Theory': 80, 'Articulate Storyline': 75, 'Storyboarding': 75, 'LMS Administration': 65},
    tools: ['Articulate Storyline', 'Adobe Captivate', 'Camtasia', 'Moodle', 'Canvas LMS'],
    aiTips: [
      'Study the ADDIE model and apply it to a sample project.',
      'Build a portfolio of interactive e-learning modules.',
      'Understand how to write clear, measurable learning objectives.',
    ],
    qualificationRequired: false,
    qualifications: [],
    qualificationNote: 'A degree in Education or Instructional Design helps, but a strong portfolio of e-learning courses is most important.',
  ),
  'academic_researcher': CareerRole(
    slug: 'academic_researcher',
    name: 'Academic Researcher',
    icon: 'education',
    category: 'Education',
    demand: 'Medium',
    salary: '₹4–12 LPA',
    color: Color(0xFF4F46E5),
    description: 'Academic Researchers conduct high-level research, publish papers in academic journals, and secure funding for ongoing study in universities or institutions.',
    requiredSkills: ['Research Methodology', 'Data Analysis', 'Academic Writing', 'Grant Writing', 'Literature Review', 'Statistical Software', 'SPSS / R'],
    weights: {'Research Methodology': 1.7, 'Academic Writing': 1.6, 'Data Analysis': 1.5, 'Literature Review': 1.4, 'Grant Writing': 1.2, 'Statistical Software': 1.1},
    requiredLevels: {'Research Methodology': 90, 'Academic Writing': 85, 'Data Analysis': 80, 'Literature Review': 85, 'Grant Writing': 70, 'Statistical Software': 75},
    tools: ['SPSS', 'R', 'MATLAB', 'Mendeley', 'LaTeX', 'EndNote'],
    aiTips: [
      'Focus strictly on peer-reviewed journals for your literature reviews.',
      'Learn LaTeX for professional paper formatting.',
      'Build relationships with senior faculty to co-author papers early in your career.',
    ],
    qualificationRequired: true,
    qualifications: ['Ph.D. or Master\'s Degree in relevant field', 'NET / JRF (in India)'],
    qualificationNote: 'You cannot become a faculty researcher without a Ph.D. and passing national eligibility tests.',
  ),
};
