import 'package:flutter/material.dart';
import '../roles_db.dart';

const Map<String, CareerRole> engineeringRoles = {
  'civil_engineer': CareerRole(
    slug: 'civil_engineer',
    name: 'Civil Engineer',
    icon: 'engineering',
    category: 'Engineering',
    demand: 'Stable',
    salary: '₹3–12 LPA',
    color: Color(0xFFEAB308),
    description: 'Civil Engineers design, build, and maintain physical structures and infrastructure like roads, bridges, and buildings.',
    requiredSkills: ['AutoCAD', 'Structural Analysis', 'Project Management', 'Surveying', 'Construction Materials', 'Revit', 'STAAD.Pro', 'Safety Regulations'],
    weights: {'AutoCAD': 1.5, 'Structural Analysis': 1.4, 'Project Management': 1.2, 'Surveying': 1.1, 'Construction Materials': 1.0, 'Revit': 1.0, 'STAAD.Pro': 1.0, 'Safety Regulations': 0.8},
    requiredLevels: {'AutoCAD': 85, 'Structural Analysis': 80, 'Project Management': 75, 'Surveying': 70, 'Construction Materials': 70, 'Revit': 70, 'STAAD.Pro': 70, 'Safety Regulations': 60},
    tools: ['AutoCAD', 'STAAD.Pro', 'Revit', 'Primavera', 'Excel'],
    aiTips: [
      'Master AutoCAD and a 3D modeling tool like Revit; they are industry standards.',
      'Gain field experience early through summer internships on construction sites.',
      'Familiarize yourself with local building codes, as they govern your designs.',
    ],
    qualificationRequired: true,
    qualifications: ['Bachelor of Technology (B.Tech) or B.E. in Civil Engineering'],
    careerCluster: 'Engineering',
    qualificationNote: 'A formal engineering degree is legally required to work as a licensed civil engineer and sign off on projects.',
  ),
  'mechanical_engineer': CareerRole(
    slug: 'mechanical_engineer',
    name: 'Mechanical Engineer',
    icon: 'engineering',
    category: 'Engineering',
    demand: 'Stable',
    salary: '₹3–14 LPA',
    color: Color(0xFFF97316),
    description: 'Mechanical Engineers design, analyze, manufacture, and maintain mechanical systems ranging from vehicles to manufacturing machinery.',
    requiredSkills: ['CAD', 'SolidWorks', 'Thermodynamics', 'Fluid Mechanics', 'ANSYS', 'Manufacturing Processes', 'Robotics', 'MATLAB'],
    weights: {'CAD': 1.5, 'SolidWorks': 1.4, 'Thermodynamics': 1.3, 'Fluid Mechanics': 1.2, 'ANSYS': 1.1, 'Manufacturing Processes': 1.2, 'Robotics': 1.0, 'MATLAB': 0.8},
    requiredLevels: {'CAD': 85, 'SolidWorks': 80, 'Thermodynamics': 75, 'Fluid Mechanics': 75, 'ANSYS': 70, 'Manufacturing Processes': 75, 'Robotics': 70, 'MATLAB': 60},
    tools: ['SolidWorks', 'AutoCAD', 'ANSYS', 'MATLAB', 'Siemens NX'],
    aiTips: [
      'Deepen your proficiency in SolidWorks or AutoCAD, going beyond fast sketches.',
      'Participate in college teams like Formula SAE to get hands-on experience.',
      'Learn basic electronics and coding (C++ or Python) to stay relevant with mechatronics.',
    ],
    qualificationRequired: true,
    qualifications: ['Bachelor of Technology (B.Tech) or B.E. in Mechanical Engineering'],
    careerCluster: 'Engineering',
    qualificationNote: 'A formal engineering degree is required for standard mechanical engineering jobs.',
  ),
  'electrical_engineer': CareerRole(
    slug: 'electrical_engineer',
    name: 'Electrical Engineer',
    icon: 'engineering',
    category: 'Engineering',
    demand: 'Stable',
    salary: '₹3–15 LPA',
    color: Color(0xFFF59E0B),
    description: 'Electrical Engineers design, develop, and test electrical equipment, from small electronic circuits to large power generators.',
    requiredSkills: ['Circuit Design', 'MATLAB', 'Power Systems', 'PLC Programming', 'AutoCAD Electrical', 'Control Systems', 'C/C++', 'Embedded Systems'],
    weights: {'Circuit Design': 1.5, 'Power Systems': 1.4, 'MATLAB': 1.2, 'Control Systems': 1.2, 'PLC Programming': 1.1, 'AutoCAD Electrical': 0.8, 'C/C++': 0.9, 'Embedded Systems': 1.0},
    requiredLevels: {'Circuit Design': 85, 'Power Systems': 80, 'MATLAB': 75, 'Control Systems': 75, 'PLC Programming': 70, 'AutoCAD Electrical': 65, 'C/C++': 60, 'Embedded Systems': 70},
    tools: ['MATLAB', 'AutoCAD Electrical', 'Simulink', 'Eagle', 'PLC Software'],
    aiTips: [
      'Learn to use simulation software like Simulink robustly.',
      'Embedded systems (Arduino, Raspberry Pi) are great transition points between hardware and software.',
      'Familiarity with PLC programming gives you a strong edge in automation and industrial applications.',
    ],
    qualificationRequired: true,
    qualifications: ['Bachelor of Technology (B.Tech) or B.E. in Electrical Engineering'],
    careerCluster: 'Engineering',
    qualificationNote: 'Formal engineering degrees are required, especially when dealing with high voltage power systems.',
  ),
};
