import 'package:flutter/material.dart';
import '../roles_db.dart';

const Map<String, CareerRole> financeRoles = {
  'financial_analyst': CareerRole(
    slug: 'financial_analyst',
    name: 'Financial Analyst',
    icon: 'finance',
    category: 'Finance',
    demand: 'High',
    salary: '₹5–18 LPA',
    color: Color(0xFF0D9488),
    description: 'Financial Analysts examine financial data and use their findings to help companies make business decisions to increase profits.',
    requiredSkills: ['Financial Modeling', 'Excel', 'Corporate Finance', 'Accounting', 'Valuation', 'Data Analysis', 'Forecasting', 'SQL'],
    weights: {'Financial Modeling': 1.6, 'Excel': 1.5, 'Valuation': 1.4, 'Corporate Finance': 1.3, 'Forecasting': 1.2, 'Accounting': 1.0},
    requiredLevels: {'Financial Modeling': 85, 'Excel': 90, 'Valuation': 80, 'Corporate Finance': 80, 'Forecasting': 75, 'Accounting': 75},
    tools: ['Excel', 'Bloomberg Terminal', 'Tableau', 'SQL', 'SAP'],
    aiTips: [
      'Master keyboard shortcuts in Excel; speed is vital during earnings seasons.',
      'Understand the three financial statements and how they link together.',
      'A master\'s degree in finance or a CFA track dramatically accelerates this career.',
    ],
    qualificationRequired: false,
    qualifications: [],
    careerCluster: 'Finance',
    qualificationNote: 'A bachelor\'s in Finance, Economics, or Accounting is heavily preferred, though CFA levels can act as a substitute.',
  ),
  'accountant': CareerRole(
    slug: 'accountant',
    name: 'Accountant',
    icon: 'finance',
    category: 'Finance',
    demand: 'Stable',
    salary: '₹3–12 LPA',
    color: Color(0xFF047857),
    description: 'Accountants prepare and examine financial records to ensure they are accurate and that taxes are paid properly and on time.',
    requiredSkills: ['Financial Reporting', 'Taxation', 'Bookkeeping', 'Excel', 'Tally', 'Auditing', 'GAAP / IFRS', 'Compliance'],
    weights: {'Financial Reporting': 1.6, 'Taxation': 1.5, 'Bookkeeping': 1.4, 'GAAP / IFRS': 1.3, 'Auditing': 1.2, 'Tally': 1.1},
    requiredLevels: {'Financial Reporting': 85, 'Taxation': 80, 'Bookkeeping': 80, 'GAAP / IFRS': 85, 'Auditing': 75, 'Tally': 70},
    tools: ['Tally', 'QuickBooks', 'Excel', 'SAP ERP', 'Zoho Books'],
    aiTips: [
      'Focus intensely on passing the CA exams if practicing in India.',
      'Familiarity with GST and local taxation laws is mandatory.',
      'Cloud accounting software (like Zoho and QuickBooks) are overtaking desktop solutions.',
    ],
    qualificationRequired: true,
    qualifications: ['Bachelor of Commerce (B.Com)', 'Chartered Accountancy (CA) / CPA / ACCA (for licensed practice)'],
    careerCluster: 'Finance',
    qualificationNote: 'To practice as a licensed auditor or chartered accountant, you must pass the respective national board exams.',
  ),
  'investment_banker': CareerRole(
    slug: 'investment_banker',
    name: 'Investment Banker',
    icon: 'finance',
    category: 'Finance',
    demand: 'High',
    salary: '₹12–50+ LPA',
    color: Color(0xFF0F766E),
    description: 'Investment Bankers help corporate clients to raise capital and provide financial advisory services, particularly for mergers and acquisitions.',
    requiredSkills: ['Financial Modeling', 'Valuation', 'M&A', 'Corporate Finance', 'Pitching', 'Excel', 'PowerPoint', 'Due Diligence'],
    weights: {'Financial Modeling': 1.7, 'Valuation': 1.6, 'M&A': 1.5, 'Corporate Finance': 1.4, 'PowerPoint': 1.2, 'Due Diligence': 1.1},
    requiredLevels: {'Financial Modeling': 90, 'Valuation': 90, 'M&A': 85, 'Corporate Finance': 85, 'PowerPoint': 80, 'Due Diligence': 80},
    tools: ['Excel', 'PowerPoint', 'Bloomberg Terminal', 'Capital IQ'],
    aiTips: [
      'Learn how to build an LBO model from scratch in under an hour.',
      'Networking is just as important as your technical skills.',
      'Attention to detail in PowerPoint pitch decks is paramount; no formatting errors allowed.',
    ],
    qualificationRequired: true,
    qualifications: ['Top-tier MBA', 'CFA (Optional but strong)'],
    careerCluster: 'Finance',
    qualificationNote: 'This role almost exclusively hires from tier-1 MBA programs or Ivy League equivalents.',
  ),
};
