import 'package:flutter/material.dart';
import '../roles_db.dart';

const Map<String, CareerRole> healthcareRoles = {
  'registered_nurse': CareerRole(
    slug: 'registered_nurse',
    name: 'Registered Nurse',
    icon: 'health',
    category: 'Healthcare',
    demand: 'Very High',
    salary: '₹3–12 LPA',
    color: Color(0xFFEF4444), // red-500
    description: 'Registered Nurses provide critical patient care, administer medications, monitor patient health, and work closely with doctors to ensure optimal recovery.',
    requiredSkills: ['Patient Care', 'EMR Proficiency', 'IV Insertion', 'Medication Administration', 'Vital Signs Monitoring', 'CPR/BLS', 'Wound Care', 'Clinical Documentation'],
    weights: {'Patient Care': 1.8, 'EMR Proficiency': 1.5, 'IV Insertion': 1.4, 'Medication Administration': 1.4, 'CPR/BLS': 1.2, 'Clinical Documentation': 1.0},
    requiredLevels: {'Patient Care': 85, 'EMR Proficiency': 80, 'IV Insertion': 75, 'Medication Administration': 80, 'CPR/BLS': 90, 'Clinical Documentation': 70},
    tools: ['Epic', 'Cerner', 'Meditech', 'Stethoscope', 'Monitoring Equipment'],
    aiTips: [
      'Gain deep familiarity with EMR systems as they are universal in modern healthcare.',
      'Obtain specialized certifications like ACLS or PALS to stand out for ICU/ER roles.',
      'Develop strong communication skills to interact effectively with patients and families.',
      'Practice situational awareness and quick decision-making for emergency response.',
    ],
    qualificationRequired: true,
    qualifications: ['Bachelor of Science in Nursing (B.Sc Nursing) or GNM', 'State Nursing License Required'],
    qualificationNote: 'This role requires a licensed nursing degree. Skills alone are not sufficient to practise.',
  ),
  'medical_officer_doctor': CareerRole(
    slug: 'medical_officer_doctor',
    name: 'Medical Officer / Doctor',
    icon: 'health',
    category: 'Healthcare',
    demand: 'Very High',
    salary: '₹6–24 LPA',
    color: Color(0xFFB91C1C),
    description: 'A licensed medical professional who diagnoses ailments, prescribes treatments, and provides comprehensive care to patients.',
    requiredSkills: ['Clinical Diagnosis', 'Patient Care', 'Medical Terminology', 'Surgery', 'EMR Proficiency', 'Pharmacology', 'Emergency Medicine'],
    weights: {'Clinical Diagnosis': 1.8, 'Patient Care': 1.5, 'Surgery': 1.4, 'Pharmacology': 1.3, 'Emergency Medicine': 1.2, 'EMR Proficiency': 1.0},
    requiredLevels: {'Clinical Diagnosis': 90, 'Patient Care': 85, 'Surgery': 80, 'Pharmacology': 85, 'Emergency Medicine': 80, 'EMR Proficiency': 70},
    tools: ['EMR Systems', 'Diagnostic Tools', 'Surgical Instruments'],
    aiTips: [
      'Focus intensely on passing licensing and residency examinations.',
      'Residency provides the actual specialization, keep studying standard protocols.',
    ],
    qualificationRequired: true,
    qualifications: ['MBBS Degree from a recognized institution', 'Medical Licensing Exam (e.g., NEXT/NEET-PG)', 'State Medical Council Registration'],
    qualificationNote: 'You cannot practice medicine without a medical degree and the mandatory licenses.',
  ),
  'pharmacist': CareerRole(
    slug: 'pharmacist',
    name: 'Pharmacist',
    icon: 'health',
    category: 'Healthcare',
    demand: 'High',
    salary: '₹2.5–8 LPA',
    color: Color(0xFF14B8A6),
    description: 'Pharmacists dispense prescription medications, offer expertise in the safe use of prescriptions, and conduct health and wellness screenings.',
    requiredSkills: ['Pharmacology', 'Medication Dispensing', 'Patient Counseling', 'Pharmacy Law', 'Inventory Management', 'FDA Regulations', 'Quality Control'],
    weights: {'Pharmacology': 1.7, 'Medication Dispensing': 1.6, 'Patient Counseling': 1.3, 'Pharmacy Law': 1.2, 'Inventory Management': 1.0},
    requiredLevels: {'Pharmacology': 90, 'Medication Dispensing': 85, 'Patient Counseling': 80, 'Pharmacy Law': 75, 'Inventory Management': 70},
    tools: ['Pharmacy Management Software', 'Inventories', 'Prescription Scanners'],
    aiTips: [
      'Pharmacovigilance is a high-growth alternative career path for pharmacists.',
      'Always stay updated with the latest drug approvals and contraindications.',
    ],
    qualificationRequired: true,
    qualifications: ['Bachelor/Master of Pharmacy (B.Pharm/M.Pharm)', 'Registered Pharmacist License'],
    qualificationNote: 'Requires formal pharmacy degrees and registration with the pharmacy council to dispense legally.',
  ),
};
