import 'package:flutter/material.dart';
import '../roles_db.dart';

const Map<String, CareerRole> marketingRoles = {
  'digital_marketer': CareerRole(
    slug: 'digital_marketer',
    name: 'Digital Marketer',
    icon: 'marketing',
    category: 'Marketing',
    demand: 'High',
    salary: '₹3–15 LPA',
    color: Color(0xFFEC4899),
    description: 'Digital Marketers plan, execute, and analyze digital advertising campaigns across varied channels including search engines, social media, and email.',
    requiredSkills: ['SEO', 'SEM', 'Social Media Marketing', 'Google Analytics', 'Content Marketing', 'Email Marketing', 'Copywriting', 'Ad Campaigns'],
    weights: {'SEO': 1.5, 'SEM': 1.4, 'Google Analytics': 1.4, 'Social Media Marketing': 1.3, 'Content Marketing': 1.2, 'Copywriting': 1.0, 'Email Marketing': 1.0, 'Ad Campaigns': 1.1},
    requiredLevels: {'SEO': 80, 'SEM': 80, 'Google Analytics': 85, 'Social Media Marketing': 80, 'Content Marketing': 75, 'Copywriting': 70, 'Email Marketing': 75, 'Ad Campaigns': 80},
    tools: ['Google Ads', 'Facebook Ads', 'Google Analytics', 'HubSpot', 'Mailchimp', 'Semrush'],
    aiTips: [
      'Earn free certifications from Google (Analytics, Ads) and HubSpot to prove your skills.',
      'A marketer is only as good as their data—learn Google Analytics deeply.',
      'Test everything with A/B tests: copy, images, demographics.',
      'Run a personal campaign or manage social media for a local business to build a portfolio.',
    ],
    qualificationRequired: false,
    qualifications: [],
    careerCluster: 'Marketing',
    qualificationNote: 'Degrees are optional; practical experience running real ad campaigns and driving real traffic counts most.',
  ),
  'seo_specialist': CareerRole(
    slug: 'seo_specialist',
    name: 'SEO Specialist',
    icon: 'marketing',
    category: 'Marketing',
    demand: 'High',
    salary: '₹3–12 LPA',
    color: Color(0xFFF43F5E),
    description: 'SEO Specialists analyze, review and implement changes to websites so they are optimized for search engines, increasing traffic and visibility.',
    requiredSkills: ['SEO', 'Keyword Research', 'On-Page Optimization', 'Off-Page SEO', 'Google Search Console', 'HTML/CSS', 'Content Strategy'],
    weights: {'SEO': 1.6, 'Keyword Research': 1.5, 'On-Page Optimization': 1.4, 'Google Search Console': 1.3, 'Off-Page SEO': 1.2, 'HTML/CSS': 0.8, 'Content Strategy': 1.1},
    requiredLevels: {'SEO': 85, 'Keyword Research': 85, 'On-Page Optimization': 80, 'Google Search Console': 80, 'Off-Page SEO': 75, 'HTML/CSS': 50, 'Content Strategy': 70},
    tools: ['Ahrefs', 'Semrush', 'Google Search Console', 'Screaming Frog', 'WordPress'],
    aiTips: [
      'Learn technical SEO inside and out—knowing how crawlers view a site is invaluable.',
      'Content is king, but backlinks are the votes. Learn ethical link building.',
      'Understand how to use Screaming Frog for deep site audits.',
    ],
    qualificationRequired: false,
    qualifications: [],
    careerCluster: 'Marketing',
    qualificationNote: 'No formal degree required—proven ability to rank web pages is what gets you hired.',
  ),
  'content_writer': CareerRole(
    slug: 'content_writer',
    name: 'Content Writer',
    icon: 'pen_tool',
    category: 'Marketing',
    demand: 'Medium',
    salary: '₹2.5–8 LPA',
    color: Color(0xFFBE185D),
    description: 'Content Writers produce engaging and informative written content for websites, blogs, and marketing materials to connect with audiences.',
    requiredSkills: ['Copywriting', 'SEO Writing', 'Research', 'Editing', 'Grammar', 'Content Strategy', 'WordPress'],
    weights: {'Copywriting': 1.6, 'SEO Writing': 1.5, 'Editing': 1.3, 'Research': 1.2, 'Grammar': 1.1, 'Content Strategy': 1.0, 'WordPress': 0.8},
    requiredLevels: {'Copywriting': 85, 'SEO Writing': 80, 'Editing': 80, 'Research': 75, 'Grammar': 85, 'Content Strategy': 70, 'WordPress': 60},
    tools: ['Grammarly', 'Google Docs', 'WordPress', 'Hemingway App', 'Ahrefs'],
    aiTips: [
      'Always write for your reader first, and for search engines second.',
      'Build a portfolio of published articles across different styles.',
      'Understand how formatting (H2s, bullet points) keeps readers engaged online.',
    ],
    qualificationRequired: false,
    qualifications: [],
    careerCluster: 'Marketing',
    qualificationNote: 'A degree in English or Journalism helps, but a portfolio of strong writing speaks louder.',
  ),
};
