import 'package:flutter/material.dart';
import '../roles_db.dart';

const Map<String, CareerRole> techRoles = {
  'flutter_developer': CareerRole(
    slug: 'flutter_developer',
    name: 'Flutter Developer',
    icon: 'code',
    category: 'Engineering',
    demand: 'High',
    salary: '₹5–22 LPA',
    color: Color(0xFF10B981),
    description: 'Flutter Developers build cross-platform mobile and web apps using Dart and the Flutter framework, delivering native-quality experiences from a single codebase.',
    requiredSkills: ['Flutter', 'Dart', 'State Management', 'REST APIs', 'Firebase', 'Git', 'UI/UX', 'Testing'],
    weights: {'Flutter': 1.8, 'Dart': 1.5, 'State Management': 1.3, 'REST APIs': 1.0, 'Firebase': 0.9, 'Git': 0.7},
    requiredLevels: {'Flutter': 85, 'Dart': 80, 'State Management': 75, 'REST APIs': 70, 'Firebase': 65, 'Git': 60},
    tools: ['VS Code', 'Android Studio', 'Firebase', 'Postman', 'Git', 'Figma'],
    aiTips: [
      'Learn Provider or Riverpod for state management — employers look for this specifically.',
      'Build 2–3 complete apps and publish them to Play Store or App Store.',
      'Study clean architecture patterns (MVVM, BLoC) for larger production projects.',
      'Contribute to open-source Flutter packages to build credibility in the community.',
    ],
    qualificationRequired: false,
    qualifications: [],
    careerCluster: 'Mobile',
    qualificationNote: 'Skills, open-source contributions, and a strong app portfolio are typically enough to get hired.',
  ),
  'devops_engineer': CareerRole(
    slug: 'devops_engineer',
    name: 'DevOps Engineer',
    icon: 'cpu',
    category: 'Infrastructure',
    demand: 'Very High',
    salary: '₹7–28 LPA',
    color: Color(0xFFFF3B6B),
    description: 'DevOps Engineers build and maintain CI/CD pipelines, manage cloud infrastructure, and ensure production systems are reliable, secure, and scalable.',
    requiredSkills: ['Docker', 'Kubernetes', 'CI/CD', 'Linux', 'AWS', 'Terraform', 'Python', 'Monitoring'],
    weights: {'Docker': 1.5, 'Kubernetes': 1.5, 'CI/CD': 1.4, 'AWS': 1.4, 'Linux': 1.1, 'Git': 0.8},
    requiredLevels: {'Docker': 80, 'Kubernetes': 80, 'CI/CD': 75, 'AWS': 75, 'Linux': 70, 'Git': 60},
    tools: ['Docker', 'Kubernetes', 'Jenkins', 'AWS', 'Terraform', 'Prometheus'],
    aiTips: [
      'Get the AWS Cloud Practitioner certification as a strong and accessible first credential.',
      'Build a home lab with Docker and Kubernetes to practice real infrastructure skills.',
      'Learn infrastructure-as-code with Terraform or Pulumi for modern cloud workflows.',
      'Contribute to open-source DevOps tools on GitHub to demonstrate real-world ability.',
    ],
    qualificationRequired: false,
    qualifications: [],
    careerCluster: 'DevOps',
    qualificationNote: 'Cloud certifications (e.g., AWS, CKA) and demonstrated experience are often valued over formal degrees.',
  ),
  'data_scientist': CareerRole(
    slug: 'data_scientist',
    name: 'Data Scientist',
    icon: 'data',
    category: 'Data & AI',
    demand: 'Very High',
    salary: '₹6–30 LPA',
    color: Color(0xFF06B6D4),
    description: 'Data Scientists extract insights from large datasets using machine learning, statistics, and visualisation tools to drive data-informed business decisions.',
    requiredSkills: ['Python', 'Machine Learning', 'SQL', 'Statistics', 'Data Visualisation', 'Pandas', 'Scikit-learn', 'Deep Learning'],
    weights: {'Python': 1.7, 'Machine Learning': 1.6, 'SQL': 1.4, 'Statistics': 1.2, 'Deep Learning': 1.2, 'Pandas': 0.9},
    requiredLevels: {'Python': 85, 'Machine Learning': 80, 'SQL': 75, 'Statistics': 75, 'Deep Learning': 70, 'Pandas': 65},
    tools: ['Jupyter', 'Python', 'TensorFlow', 'Tableau', 'SQL', 'Spark'],
    aiTips: [
      'Build end-to-end ML projects with real datasets on Kaggle to develop practical skills.',
      'Learn SQL deeply — data wrangling represents 80% of the actual job.',
      'Understand statistics fundamentals: distributions, hypothesis testing, A/B tests.',
    ],
    qualificationRequired: false,
    qualifications: [],
    careerCluster: 'Data',
    qualificationNote: 'A relevant degree is highly preferred, but strong practical projects and math fundamentals can substitute.',
  ),
  'cybersecurity_analyst': CareerRole(
    slug: 'cybersecurity_analyst',
    name: 'Cybersecurity Analyst',
    icon: 'security',
    category: 'Security',
    demand: 'High',
    salary: '₹5–20 LPA',
    color: Color(0xFFDC2626),
    description: 'Cybersecurity Analysts protect networks and data from breaches by monitoring for vulnerabilities, defending against attacks, and implementing security measures.',
    requiredSkills: ['Network Security', 'Linux', 'Ethical Hacking', 'SIEM', 'Risk Management', 'Cryptography', 'Python', 'Incident Response'],
    weights: {'Network Security': 1.6, 'Linux': 1.4, 'Incident Response': 1.3, 'SIEM': 1.3, 'Ethical Hacking': 1.2, 'Python': 0.8},
    requiredLevels: {'Network Security': 85, 'Linux': 80, 'Incident Response': 75, 'SIEM': 75, 'Ethical Hacking': 70, 'Python': 60},
    tools: ['Wireshark', 'Kali Linux', 'Splunk', 'Metasploit', 'Nmap'],
    aiTips: [
      'Start by getting the CompTIA Security+ certification.',
      'Practice hands-on penetration testing on Hack The Box or TryHackMe.',
      'Learn scripting (like Python) to automate mundane security tasks.',
    ],
    qualificationRequired: false,
    qualifications: [],
    careerCluster: 'Security',
    qualificationNote: 'Valuable industry certifications (Security+, CISSP, CEH) matters much more than degrees.',
  ),
  'ai_engineer': CareerRole(
    slug: 'ai_engineer',
    name: 'AI Engineer',
    icon: 'cpu',
    category: 'Data & AI',
    demand: 'Very High',
    salary: '₹10–40 LPA',
    color: Color(0xFF2563EB),
    description: 'AI Engineers build, test, and deploy AI models (like LLMs or computer vision models) to create intelligent systems and applications.',
    requiredSkills: ['Python', 'Deep Learning', 'PyTorch', 'TensorFlow', 'NLP', 'Computer Vision', 'Generative AI', 'Model Deployment'],
    weights: {'Deep Learning': 1.6, 'Python': 1.5, 'PyTorch': 1.4, 'Generative AI': 1.3, 'NLP': 1.2, 'Model Deployment': 1.1},
    requiredLevels: {'Deep Learning': 85, 'Python': 85, 'PyTorch': 80, 'Generative AI': 75, 'NLP': 70, 'Model Deployment': 70},
    tools: ['PyTorch', 'Hugging Face', 'TensorFlow', 'Docker', 'AWS'],
    aiTips: [
      'Master the transformers architecture and how to fine-tune open-source models (Llama, Mistral).',
      'Learn deployment frameworks like vLLM or Onyx for low latency serving.',
      'Contribute to open source AI communities on GitHub or Hugging Face.',
    ],
    qualificationRequired: false,
    qualifications: [],
    careerCluster: 'AI',
    qualificationNote: 'High technical bar. Formal advanced degrees are very common but a stellar track record building and deploying complex AI systems can suffice.',
  ),
};
